- name: get all running vms
  virt:
    command: list_vms
  register: vms

- name: deploy virt-install {{ vm_name }} template
  template:
    src: virt-install-coreos.j2
    dest: "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ admin_user }}"
  when: vm_type == "bootstrap"

- name: deploy vm instance {{ vm_name }}
  shell:  "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
  become: true
  register: deploy_vm_instance
  until: deploy_vm_instance.rc == 0
  delay: 1
  retries: 5
  when: vm_type == "bootstrap"

- name: deploy virt-install {{ vm_name }} template
  template:
    src: virt-install-coreos.j2
    dest: "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ admin_user }}"
  when: vm_type == "master"

- name: deploy vm instance {{ vm_name }}
  shell:  "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
  become: true
  register: deploy_vm_instance
  until: deploy_vm_instance.rc == 0
  delay: 1
  retries: 5
  when: vm_type == "master"

- name: deploy virt-install {{ vm_name }} template
  template:
    src: virt-install-coreos.j2
    dest: "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ admin_user }}"
  when: vm_type == "worker"

- name: deploy vm instance {{ vm_name }}
  shell:  "{{ coreos_iso_extract_dir }}/{{ vm_name }}.sh"
  become: true
  register: deploy_vm_instance
  until: deploy_vm_instance.rc == 0
  delay: 1
  retries: 5
  when: vm_type == "worker"
