---
# tasks file for swygue.coreos-virt-install-iso#!/usr/bin/env ansible-playbook
- name: setup files to be servered up via webserver for ignition
  include: setup_httpd_files.yml

- name: check if podman webserver is exists
  shell: podman ps -a | grep {{ podman_webserver }}
  become: yes
  failed_when: false
  changed_when: webserver_exist.rc != 0
  register: webserver_exist

- name: debug webserver_exist
  debug: var=webserver_exist

- name: check if podman webserver is Running 
  shell: podman inspect {{ podman_webserver }} | grep Running |grep true
  become: yes
  failed_when: false
  register: webserver_running

- name: include podman start/deploy tasks
  include: start_podman_webserver.yml
