---
- name: build podman webserver if not deployed
  command: podman build --format=docker -t webserver .
  become: yes
  args:
    chdir: "{{ coreos_tmp_dir }}/webserver"
    warn: false
  when: webserver_exist.rc != 0

- name: create podman webserver 
  command: podman create -v {{ webserver_directory }}:/var/www/html/pub:Z -p 8080:80 --name={{ podman_webserver }} webserver
  become: yes
  args:
    warn: false
  when: webserver_exist.rc != 0

- name: start stopped podman webserver
  command: podman start {{ podman_webserver }}
  become: yes
  args:
    warn: false
  when: webserver_running.rc != 0